name: Build Mobile Apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web app with Angular CLI
      run: npx ng build
    
    - name: Sync Capacitor
      run: npx cap sync android
    
    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug
    
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web app with Angular CLI
      run: npx ng build
    
    - name: Sync Capacitor
      run: npx cap sync ios
    
    - name: Install CocoaPods
      run: |
        cd ios/App
        pod install
    
    - name: List available simulators
      run: xcrun simctl list devices available
    
    - name: Build iOS App
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace -scheme App -destination 'generic/platform=iOS Simulator' -derivedDataPath build clean build
    
    - name: Upload iOS App
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: ios/App/build/Build/Products/Debug-iphonesimulator/App.app
